### ISSUE TITLE
Can't compile on Raspbian

### ISSUE THREAD

**Issue by TheNickoos** [sashakh/waze#10]
Hi there !
Got some compilation error on rapberry os.

> roadmap_screen.c:3207:22: error: ‘dec_close’ undeclared (first use in this function)
  ssd_dialog_hide_all(dec_close);
                      ^~~~~~~~~
roadmap_screen.c:3207:22: note: each undeclared identifier is reported only once for each function it appears in
roadmap_screen.c: In function ‘roadmap_screen_is_xicon_open’:
roadmap_screen.c:4032:9: error: ‘isXIconOpen’ undeclared (first use in this function)
  return isXIconOpen;
         ^~~~~~~~~~~
roadmap_screen.c: In function ‘XiconTimer’:
roadmap_screen.c:4036:2: error: ‘isXIconOpen’ undeclared (first use in this function)
  isXIconOpen = FALSE;
  ^~~~~~~~~~~
roadmap_screen.c: In function ‘roadmap_screen_set_Xicon_state’:
roadmap_screen.c:4043:5: error: ‘isXIconOpen’ undeclared (first use in this function)
  if(isXIconOpen){
     ^~~~~~~~~~~

> 
:(
Thanks for the help :)

**Comment by sashakh** [comment]
Hi, Looks that you are not build properly. Run ```make``` on top of the tree (one level above ```src/``` directory). See README file.

**Comment by sashakh** [comment]
Also it looks that your source tree is outdated. The line referenced by error in ```roadmap_screen.c``` is 3973 and not 3207.
