### ISSUE TITLE
Raspberry Pi 3

### ISSUE THREAD

**Issue by kessyus** [sashakh/waze#2]
Hey Sashakh!

I found very interesting your idea and now I'm trying to build Waze for a Raspberry Pi. I did install all packages you mentioned and compiled the program with no errors. After I launched the program it asks me to set the language -> ok, then it asks me to accept the agreement -> ok once again, then the next screen it closes unexpectally and after I try to open again it says:

19:45:34.000 sERROR !!! ../agg/roadmap_canvas.cpp, line 920 roadmap_canvas_agg_configure, height =575 width=800     [File: '../agg/roadmap_canvas.cpp'; Line: 920]
19:45:34.029 sERROR !!! roadmap_sprite.c, line 299 first plane of sprite GPS is missing     [File: 'roadmap_sprite.c'; Line: 299]
19:45:34.047 sERROR !!! roadmap_prompts.c, line 314 prompts.conf not found.     [File: 'roadmap_prompts.c'; Line: 314]
19:45:34.191 sERROR !!! address_search/single_search.c, line 101 single_search_init() - 'wst_init()' failed     [File: 'address_search/single_search.c'; Line: 101]
19:45:34.200 sERROR !!! roadmap_start.c, line 2992 Waze did not close properly [File: 'roadmap_start.c'; Line: 2992]
19:45:34.201 sERROR !!! Realtime/RealtimeNet.c, line 367 RTNet_LoadParams() - Invalid web-service address (https://rtproxy-row.waze.com:443/rtserver)   [File: 'Realtime/RealtimeNet.c'; Line: 367]
waze: websvc_trans/websvc_trans.c:183: wst_init: Assertion `0' failed.

I believe the error is that the server https://rtproxy-row.waze.com/rtserver (it is a 443 msg) is not available anymore. Do you happen to know how to fix it? Maybe if we try a recent version of Waze?

Best Regards, Kes

**Comment by sashakh** [comment]
Hi Kes,

It looks that this version of waze doesn't support https:// normally and once waze server worked over http://. You can try something simple like:

```
diff --git a/src/websvc_trans/websvc_address.c b/src/websvc_trans/websvc_address.c
index 1c7277c..a432670 100644
--- a/src/websvc_trans/websvc_address.c
+++ b/src/websvc_trans/websvc_address.c
@@ -85,13 +85,17 @@ BOOL   WSA_ExtractParams(
    for( i=0; i<strlen(szWebServiceAddress); i++)
       Copy[i] = szWebServiceAddress[i];
    Copy[i] = '\0';
-   
-   //   Search for 'http://':
-   if( 0 != strncasecmp( (const char*)Copy, WSA_PREFIX, WSA_PREFIX_SIZE))
+  
+   unsigned int is_https = 0;
+ 
+   //   Search for 'http://': or https://
+   if( !strncasecmp( (const char*)Copy, "https://", WSA_PREFIX_SIZE + 1))
+       is_https = 1;
+   else if( 0 != strncasecmp( (const char*)Copy, WSA_PREFIX, WSA_PREFIX_SIZE))
       return FALSE;
 
    //   Server URL:
-   pSrvURL = (Copy + WSA_PREFIX_SIZE);
+   pSrvURL = (Copy + WSA_PREFIX_SIZE + is_https);
    
    //   Do we have a port number?
    pTmp = strchr( pSrvURL, WSA_SERVER_PORT_DELIMITER);
```

**Comment by sashakh** [comment]
Regarding upgrade to recent sources. Idea is good basically, do you have a time to do it? )
Also as far as I know the recent version of Waze sources published is 2.4.0.0 (you can find it also in this repository under android-2.4.0.0 tag or android branch), however version available in PlayStore is 4.9.0.2.

**Comment by sashakh** [comment]
Hi again, Kes!

Actually I've upgraded to based on 2.4. And after some quick porting it just works without problem fo me. )
Please try and report. Thanks!

Sasha

**Comment by sashakh** [comment]
Please note that you will need libssl-dev installed for this new version.

**Comment by sashakh** [comment]
No complines. Closing.
