### ISSUE TITLE
Segmentation error

### ISSUE THREAD

**Issue by lordkkjmix** [sashakh/waze#3]
Hi,
I check your API but i got segmentation error.
How to resolve it.
Check the screenshot
Thx
![capture du 2017-01-31 17-20-00](https://cloud.githubusercontent.com/assets/13110088/22476258/94174bc8-e7d9-11e6-87b3-ef2818959533.png)

**Comment by sashakh** [comment]
It is waze, not my errors. Be sure that you have everything installed. The failure is related to missing config file (I guess).

**Comment by sashakh** [comment]
BTW is it linux at all? )

**Comment by lordkkjmix** [comment]
Thx for your answer, i use only linux, when i login the app close automaticly.

**Comment by sashakh** [comment]
I think that something is missing in the installation (prompts.conf file). Be sure that you installed user part with 'make install-user'. In any case you can investigate the core file with:

  gdb /path/to/waze -c core

**Comment by sashakh** [comment]
No answer. Closing.
