### ISSUE TITLE
Typo in readme

### ISSUE THREAD

**Issue by campbellwb** [sashakh/waze#6]
Hi,
Just noticed a typo in the readme.
Instead of -lidssl-dev it should say -libssl-dev

Love the repo! Waze on my car-pi is amazing.

**Comment by sashakh** [comment]
Fixed, Thanks!

**Comment by sashakh** [comment]
BTW, are you using waze with GPS successfully? Is it gpsd?
Some guys have an issues with it. #4 . So I'm asking. Thanks.
